;;;(include 'identity "./flow/identity")

;;;(identity object)
;;;
;;;object : atom or list
;;;
;;;return : object

;;; +------------------------------------------------------+
;;;   Copyright (c) 2020 manual chair japan                 
;;;   Released under the MIT license                        
;;;   https://opensource.org/licenses/mit-license.php       
;;; +------------------------------------------------------+

(defun identity (object)
  object
)