;;;(include 'tan "./numbers/tan")

;;; +------------------------------------------------------+
;;;   Copyright (c) 2020 manual chair japan                 
;;;   Released under the MIT license                        
;;;   https://opensource.org/licenses/mit-license.php       
;;; +------------------------------------------------------+

(defun tan (radian) (/ (sin radian) (cos radian)))

;;;(setq tan acet-calc-tan)
